In [1]:
import pandas as pd
import logging

In [20]:
df = pd.read_excel('../data/raw/PlantData.xlsx')

In [21]:
df.head()

,PlantCode,DispPlantCode,PlantName,PlantNameEn,ZoneCode,ZoneName,PlantType,BusCode,UTM,ProvinceCode,ProvinceName
0,MZ014W,MZ014,بادي کهک 3,Badi kahak 3,R05,زنجان,W,196781,"36.024042,49.602063",P18,قزوين
1,MZ008W,MZ008,بادي کهک 2,badi kahak 2,R05,زنجان,W,196781,"36.024042,49.602063",P18,قزوين
2,ME019G,ME019,کالاي الکتريک,Serkate kalaye electric,R09,اصفهان,G,905191,"27.448737475706977,52.74557708990336",P07,بوشهر
3,I902G,I902,پتروشیمی دماوند گاز,Petroshimi Damavand,R11,فارس,G,978191,"27.73126798352448, 52.17296722350121",P07,بوشهر
4,I902_1G,I902_1,پتروشیمی دماوند گاز,Petroshimi Damavand,R11,فارس,G,978191,"27.73126798352448, 52.17296722350121",P07,بوشهر

In [22]:
df = df[['DispPlantCode', 'PlantName', 'PlantType', 'UTM']]
df.head()

,DispPlantCode,PlantName,PlantType,UTM
0,MZ014,بادي کهک 3,W,"36.024042,49.602063"
1,MZ008,بادي کهک 2,W,"36.024042,49.602063"
2,ME019,کالاي الکتريک,G,"27.448737475706977,52.74557708990336"
3,I902,پتروشیمی دماوند گاز,G,"27.73126798352448, 52.17296722350121"
4,I902_1,پتروشیمی دماوند گاز,G,"27.73126798352448, 52.17296722350121"

In [3]:
! pip install numpy

Requirement already satisfied: numpy in /home/hajali/Desktop/Bargh_Ml_project/BarghProject/lib/python3.12/site-packages (2.2.1)

In [1]:
from ..logs.logger import CustomLogger

ImportError: attempted relative import with no known parent package

In [2]:
from logs import logger

ModuleNotFoundError: No module named 'logs'

In [2]:
logging.basicConfig(
    filename='log_file.log',
    level=logging.INFO,
    format='[%(asctime)s] {%(pathname)s:%(lineno)d} %(levelname)s - %(message)s',
    datefmt='%H:%M:%S',
    filemode='a'
)

class SummaryFormatter(logging.Formatter):
    def format(self, record):
        if record.levelname == 'ERROR':
            return f"{record.levelname}: {record.name}: {record.message[:50]}"  # Summary of error
        return super().format(record)

console = logging.StreamHandler()
console.setLevel(logging.INFO)

formatter = logging.Formatter('%(name)-12s%(levelname)-8s')
summaryFormatter = SummaryFormatter()
console.setFormatter(summaryFormatter)

logging.getLogger('').addHandler(console)

logger = logging.getLogger(__name__)

In [19]:
class CustomLogger:
    def __init__(self, name: str, log_gile: str):
        self.logger = logging.getLogger(name=name)
        self.logger.setLevel(logging.DEBUG)
        
        file_handler = logging.FileHandler(log_gile)
        file_handler.setLevel(logging.DEBUG)

        console_handler = logging.StreamHandler()
        console_handler.setLevel(logging.INFO)

        formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')

        file_handler.setFormatter(formatter)
        console_handler.setFormatter(formatter)

        if not self.logger.handlers:
            self.logger.addHandler(file_handler)
            self.logger.addHandler(console_handler)
    

    def debug(self, msg: str):
        self.logger.debug(msg=msg)
    
    def info(self, msg: str):
        self.logger.info(msg=msg)
    
    def warning(self, msg: str):
        self.logger.warning(msg=msg)
    
    def error(self, msg: str):
        self.logger.error(msg=msg)
    
    def critical(self, msg: str):
        self.logger.critical(msg=msg)

In [44]:
logger = CustomLogger(__name__, log_gile='log_file.log')
logger.info('hello im testing the logger file')

2025-02-13 19:46:33,069 - __main__ - INFO - hello im testing the logger file

In [45]:
try:
    print(len(logger))
except Exception as e:
    logger.error(f'Exceprtion: {e} happened')

2025-02-13 19:47:44,460 - __main__ - ERROR - Exceprtion: object of type 'CustomLogger' has no len() happened

In [3]:
def drop_columns(input_file: str, columns: list[str], is_xlsx=False) -> pd.DataFrame:
    try:
        if is_xlsx:
            df = pd.read_excel(input_file)
        else:
            df = pd.read_csv(input_file)
        
        logging.info(msg=f'{input_file} successfully saved in pandas dataframe.')

        df = df[columns]
        df.dopna(axis=0, inplace=True)
        df.drop_duplicates(inplace=True)
        return df

    except Exception as e:
        logging.warning(msg=f'Exception --""{e}""-- occured and couldnt get the data.')
        return None

In [39]:
l = {
    'ali': 'baba',
    'mahdi': 'hossein'
}
a = [f'{col_name} {col_type}' for col_name, col_type in l.items()]
b = ', '.join(a)
print(b)
print(*a, sep=', ')

ali baba, mahdi hossein
ali baba, mahdi hossein

In [2]:
from enum import Enum

In [3]:
class RawData(Enum):
    BAR = '/home/hajali/Desktop/Bargh_Ml_project/data/raw/LowMiddlePeakLoadHours_View.xlsx'
    PLANT = '/home/hajali/Desktop/Bargh_Ml_project/data/raw/PlantData.xlsx'
    TEMPERATURE = '/home/hajali/Desktop/Bargh_Ml_project/data/raw/PlantsTemperature_View.xlsx'
    ENERGY = '/home/hajali/Desktop/Bargh_Ml_project/data/raw/PowerplantUnitEnergy_View.csv'
    SELLEROFFER = '/home/hajali/Desktop/Bargh_Ml_project/data/raw/SellerOffer_View.csv'
    FACTORS = '/home/hajali/Desktop/Bargh_Ml_project/data/raw/TemperatureFactors_View(140304,140307,140309).xlsx'
    STATUS = '/home/hajali/Desktop/Bargh_Ml_project/data/raw/UnitsStatusChange_Hourly_View.csv'

In [4]:
print(type(RawData.__members__))
if isinstance(RawData.BAR, RawData):
    print('yes')

<class 'mappingproxy'>
yes

In [5]:
import os
import sys

In [6]:
project_root = os.path.abspath("/home/hajali/Desktop/Bargh_Ml_project/")
sys.path.insert(0, project_root)

In [7]:
from logs.logger import CustomLogger

In [8]:
from src.data.dbconnection import Database

In [9]:
import psycopg2

In [11]:
df = pd.read_csv(RawData.ENERGY.value)
df.head()

,DispPlantCode,UnitCode,Name,Date,h1,h2,h3,h4,h5,h6,...,H15,H16,H17,H18,H19,H20,H21,H22,H23,H24
0,451,H2,سد کوهرنگ,1403/07/05,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.041667,3.302000,0.544333,0.0,0.0,0.0
1,451,H2,سد کوهرنگ,1403/07/09,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.010667,3.261000,0.290000,0.0,0.0,0.0
2,451,H2,سد کوهرنگ,1403/07/10,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,2.944667,0.320333,0.0,0.0,0.0
3,451,H2,سد کوهرنگ,1403/07/06,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.133000,3.281666,0.209000,0.0,0.0,0.0
4,451,H2,سد کوهرنگ,1403/07/08,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.164000,3.078333,0.178000,0.0,0.0,0.0

In [8]:
df_melted = pd.melt(df, id_vars=['DispPlantCode', 'UnitCode', 'Name', 'Date'], value_vars=['h{}'.format(i) for i in range(1, 10)] + ['H{}'.format(i) for i in range(10, 25)], var_name='hour', value_name='generation')
df_melted['hour'] = df_melted['hour'].str.replace('h', '')
df_melted['hour'] = df_melted['hour'].str.replace('H', '')
df_melted['hour'] = df_melted['hour'].astype(int)
df_melted.head()

  DispPlantCode UnitCode       Name        Date  hour  generation
0           451       H2  سد کوهرنگ  1403/07/05     1         0.0
1           451       H2  سد کوهرنگ  1403/07/09     1         0.0
2           451       H2  سد کوهرنگ  1403/07/10     1         0.0
3           451       H2  سد کوهرنگ  1403/07/06     1         0.0
4           451       H2  سد کوهرنگ  1403/07/08     1         0.0

In [19]:
max_indices = df_melted.groupby(['DispPlantCode', 'UnitCode', 'Name', 'Date'])['hour'].idxmax()
result = df.loc[max_indices]
result.head()

KeyError: "None of [Index([178858, 178860, 178857, 178863, 178868, 178859, 178869, 178862, 178861,\n       178867,\n       ...\n       184450, 184606, 184602, 184605, 184451, 184603, 184604, 184453, 184454,\n       184452],\n      dtype='int64', length=7472)] are in the [index]"

In [9]:
df_melted.to_csv('../temp/melt.csv')

In [21]:
df = pd.read_csv(RawData.SELLEROFFER.value)
df.head()

/tmp/ipykernel_5567/226274280.py:1: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(RawData.SELLEROFFER.value)

,FullUnitCode,Date,PowerPlantCode,PowerPlantName,UnitCode,Code,Revision,InsertDateTime,IsLastRevision,Description,...,Price16,Power17,Price17,Power18,Price18,Power19,Price19,Power20,Price20,Comment
0,181-G11,1403/07/01,181,آریان,G11,4914936,3,1403/06/31-13:32:11.22,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,دمای اگزوز
1,181-G11,1403/07/01,181,آریان,G11,4914936,3,1403/06/31-13:32:11.22,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,دمای اگزوز
2,181-G11,1403/07/01,181,آریان,G11,4914936,3,1403/06/31-13:32:11.22,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,دمای اگزوز
3,181-G11,1403/07/01,181,آریان,G11,4914936,3,1403/06/31-13:32:11.22,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,دمای اگزوز
4,181-G11,1403/07/01,181,آریان,G11,4914936,3,1403/06/31-13:32:11.22,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,دمای اگزوز

In [24]:
df = df[['PowerPlantCode', 'PowerPlantName', 'UnitCode', 'Date', 'HourNo', 'Revision', 'Declared']]
df.head()

,PowerPlantCode,PowerPlantName,UnitCode,Date,HourNo,Revision,Declared
0,181,آریان,G11,1403/07/01,10,3,142.0
1,181,آریان,G11,1403/07/01,9,3,144.0
2,181,آریان,G11,1403/07/01,8,3,146.0
3,181,آریان,G11,1403/07/01,7,3,148.0
4,181,آریان,G11,1403/07/01,6,3,149.0

In [26]:
max_indices = df.groupby(['PowerPlantCode', 'PowerPlantName', 'UnitCode', 'Date', 'HourNo'])['Revision'].idxmax()
result = df.loc[max_indices]
result.head()

,PowerPlantCode,PowerPlantName,UnitCode,Date,HourNo,Revision,Declared
4845,101,بعثت,S1,1403/07/01,1,8,60.0
4847,101,بعثت,S1,1403/07/01,2,8,60.0
4849,101,بعثت,S1,1403/07/01,3,8,60.0
4851,101,بعثت,S1,1403/07/01,4,8,60.0
5047,101,بعثت,S1,1403/07/01,5,8,60.0

In [27]:
print(len(df.index))
print(len(result.index))

198960
132507

In [28]:
df = pd.read_csv(RawData.STATUS.value)
df.head()

,FullUnitCode,Date,Revision,Hour,AvailableValue,CauseCode,CauseName,UnitStateTypeCode,UnitStateTypeName,ActualValue
0,610-G11,1403/07/01,3,11,0.0,Z2,یاتاقان,FO,خروج اضطراری,17.3
1,610-G11,1403/07/01,3,12,0.0,Z2,یاتاقان,FO,خروج اضطراری,17.3
2,610-G11,1403/07/01,3,13,0.0,Z2,یاتاقان,FO,خروج اضطراری,17.3
3,610-G11,1403/07/01,3,14,0.0,Z2,یاتاقان,FO,خروج اضطراری,17.3
4,610-G11,1403/07/01,3,15,0.0,Z2,یاتاقان,FO,خروج اضطراری,17.3

In [29]:
df[['id', 'code']] = df['FullUnitCode'].str.split('-', expand=True)
df.head()

,FullUnitCode,Date,Revision,Hour,AvailableValue,CauseCode,CauseName,UnitStateTypeCode,UnitStateTypeName,ActualValue,id,code
0,610-G11,1403/07/01,3,11,0.0,Z2,یاتاقان,FO,خروج اضطراری,17.3,610,G11
1,610-G11,1403/07/01,3,12,0.0,Z2,یاتاقان,FO,خروج اضطراری,17.3,610,G11
2,610-G11,1403/07/01,3,13,0.0,Z2,یاتاقان,FO,خروج اضطراری,17.3,610,G11
3,610-G11,1403/07/01,3,14,0.0,Z2,یاتاقان,FO,خروج اضطراری,17.3,610,G11
4,610-G11,1403/07/01,3,15,0.0,Z2,یاتاقان,FO,خروج اضطراری,17.3,610,G11

In [ ]:
class csvfile_manipulation:
    def __init__(self):
        pass
    
    def clean(self, input_file: str, columns=list[str], is_xlsx=False, melt=False) -> pd.DataFrame:
        try:
            if is_xlsx:
                df = pd.read_excel(input_file)
            else:
                df = pd.read_csv(input_file)
            
            logger.info(msg=f'{input_file} successfully saved in pandas dataframe.')

            if melt:

                try:
                    df = pd.melt(
                        df, id_vars=['DispPlantCode', 'UnitCode', 'Name', 'Date'],
                        value_vars=['h{}'.format(i) for i in range(1, 10)] + ['H{}'.format(i) for i in range(10, 25)],
                        var_name='hour',
                        value_name='generation'
                    )

                    df['hour'] = df['hour'].str.replace('h', '')
                    df['hour'] = df['hour'].str.replace('H', '')
                    df['hour'] = df['hour'].astype(int)

                    logger.info()
                except Exception as e:
                    logger.error()


            df = df[columns]
            df.dropna(axis=0, inplace=True)
            df.drop_duplicates(inplace=True)
            return df

        except Exception as e:
            logger.warning(msg=f'Exception --""{e}""-- occured and couldnt get the data.')
            return None
    
    def process(self, file: RawData):
        db = Database()
        db.connect()


        match file:


            case RawData.BAR:
                table_name = 'bar'
                df = self.clean(input_file=file.value, is_xlsx=True)
                try:

                    df.to_csv(path_or_buf='/home/hajali/Desktop/Bargh_Ml_project/temp/bartemp.csv', sep=',', header=True, index=False, na_rep='NULL')
                    db.execute(
                        query=f'create table if not exists {table_name}  (date text, hour int, value varchar(10));'
                    )
                    db.commit()


                    db.copy_expert(
                        query=f"copy {table_name} from stdin with delimiter ',' csv header NULL as 'NULL'",
                        file='/home/hajali/Desktop/Bargh_Ml_project/temp/bartemp.csv',
                        mode='r'
                    )
                    db.commit()


                    db.__exit__()
                except psycopg2.Error as e:
                    logger.error()
                    if db.connection:
                        db.rollback()
                
                try:
                    db.__enter__()

                    db.copy_expert(
                        query=f"copy {table_name} to stdout with delimiter ',' csv header NULL as 'NULL'",
                        file='/home/hajali/Desktop/Bargh_Ml_project/data/interim/bar.csv',
                        mode='w'
                    )
                    
                    db.commit()
                    db.__exit__()
                except psycopg2.Error as e:
                    logger.error()
                    if db.connection:
                        db.rollback()
                
                os.remove('/home/hajali/Desktop/Bargh_Ml_project/temp/bartemp.csv')
            

            case RawData.PLANT:
                table_name = 'plant_data'
                df = self.clean(input_file=file.value, columns=['DispPlantCode', 'PlantName', 'PlantType', 'UTM'], is_xlsx=True)

                try:

                    df.to_csv(path_or_buf='/home/hajali/Desktop/Bargh_Ml_project/temp/plantdata.csv', sep=',', header=True, index=False, na_rep='NULL')
                    db.execute(
                        query=f'create table if not exists {table_name} (id varchar(50), name varchar(100), type varchar(10), UTM text)',
                        do_return=False
                    )
                    db.commit()

                    db.copy_expert(
                        query=f"copy {table_name} from stdin with delimiter ',' csv header NULL as 'NULL'",
                        file='/home/hajali/Desktop/Bargh_Ml_project/temp/plantdata.csv',
                        mode='r'
                    )
                    db.commit()

                    db.__exit__()
                except psycopg2.Error as e:
                    logger.error()
                    if db.connection:
                        db.rollback()
                
                try:
                    db.__enter__()

                    db.copy_expert(
                        query=f"copy {table_name} to stdout with delimiter ',' csv header NULL as 'NULL'",
                        file='/home/hajali/Desktop/Bargh_Ml_project/data/interim/plant_data.csv',
                        mode='w'
                    )
                    db.commit()

                    db.__exit__()
                except psycopg2.Error as e:
                    logger.error()
                    if db.gconnection:
                        db.rollback()
                
                os.remove('/home/hajali/Desktop/Bargh_Ml_project/temp/plantdata.csv')

            

            case RawData.TEMPERATURE:
                table_name = 'plant_temp'
                df = self.clean(input_file=file.value, columns=['PowerPlantCode', 'PowerPlantName', 'Date', 'HourNo', 'Value'], is_xlsx=True)

                try:
                    df.to_csv(path_or_buf='/home/hajali/Desktop/Bargh_Ml_project/temp/temperature.csv', sep=',', header=True, index=False, na_rep='NULL')
                    db.execute(
                        query=f'create table if not exists {table_name} (id varchar(50), name varchar(100), date text, hour int, temperature float)',
                        do_return=False
                    )
                    db.commit()

                    db.copy_expert(
                        query=f"copy {table_name} from stdin with delimiter ',' csv header NULL as 'NULL'",
                        file='/home/hajali/Desktop/Bargh_Ml_project/temp/temperature.csv',
                        mode='r'
                    )
                    db.commit()

                    db.__exit__()
                except psycopg2.Error as e:
                    logger.error()
                    if db.connection:
                        db.rollback()
                
                try:
                    db.execute(
                        query=f'create table plants_mean_temp as (select id, name, date, hour, avg(temperature) as mean_temp from plant_temp group by id, name, date, hour)',
                        do_return=False
                    )
                    db.commit()
                except psycopg2.Error as e:
                    logger.error()
                    if db.connection:
                        db.rollback()
                


            case RawData.ENERGY:
                table_name = 'energy'
                df = self.clean(input_file=file.value, is_xlsx=False, melt=True)

                try:
                    df.to_csv(path_or_buf='/home/hajali/Desktop/Bargh_Ml_project/temp/energy.csv', sep=',', header=True, index=False, na_rep='NULL')
                    db.execute(
                        query=f'create table if not exists {table_name} (id varchar(50), code varchar(50), name varchar(100), date text, hour int, generation float);',
                        do_return=False
                    )
                    db.commit()

                    db.copy_expert(
                        query=f"copy {table_name} from stdin delimiter ',' csv header NULL as 'NULL'",
                        file='/home/hajali/Desktop/Bargh_Ml_project/temp/energy.csv',
                        mode='r'
                    )
                    db.commit()

                    db.__exit__()
                except psycopg2.Error as e:
                    logger.error()
                    if db.connection:
                        db.rollback()
                

                try:
                    db.__enter__()
                    
                    db.copy_expert(
                        query=f"copy {table_name} to stdout with delimiter ',' csv header NULL as 'NULL'",
                        file='/home/hajali/Desktop/Bargh_Ml_project/data/interim/energy.csv',
                        mode='w'
                    )

                    db.commit()

                    db.__exit__()

                except psycopg2.Error as e:
                    logger.error()
                    if db.connection:
                        db.rollback()
                

            case RawData.SELLEROFFER:
                table_name = 'selleroffer'
                df = self.clean(input_file=file.value, is_xlsx=False)

                try:
                    max_indices = df.groupby(['PowerPlantCode', 'PowerPlantName', 'UnitCode', 'Date', 'HourNo'])['Revision'].idxmax()
                    result = df.loc[max_indices]
                    result.drop(columns=['Revision'], axis=1, inplace=True)
                    result.to_csv(path_or_buf='/home/hajali/Desktop/Bargh_Ml_project/temp/selleroffer.csv', sep=',', header=True, index=False, na_rep='NULL')

                    db.execute(
                        query=f"create table if not exists {table_name} (id varchar(10), name varchar(100), code varchar(10), date text, hour int, declare float)",
                        do_return=False
                    )
                    db.commit()

                    db.copy_expert(
                        query=f"copy {table_name} from stdin delimiter ',' csv header NULL as 'NULL'",
                        file='/home/hajali/Desktop/Bargh_Ml_project/temp/selleroffer.csv',
                        mode='r'
                    )
                    db.commit()

                    db.__exit__()
                except Exception as e:
                    logger.error()
                    if db.connection:
                        db.rollback()
                

                try:
                    db.__enter__()
                    
                    db.copy_expert(
                        query=f"copy {table_name} to stdout with delimiter ',' csv header NULL as 'NULL'",
                        file='/home/hajali/Desktop/Bargh_Ml_project/data/interim/selleroffer.csv',
                        mode='w'
                    )

                    db.commit()

                    db.__exit__()

                except psycopg2.Error as e:
                    logger.error()
                    if db.connection:
                        db.rollback()
                

            case RawData.FACTORS:
                table_name = 'factors'
                df = self.clean(input_file=file.value, is_xlsx=False)

                try:
                    df.to_csv(path_or_buf='/home/hajali/Desktop/Bargh_Ml_project/temp/factors.csv', sep=',', header=True, index=False, na_rep='NULL')
                    db.execute(
                        query=f'create table if not exists {table_name} (id varchar(50), name varchar(100), code varchar(50), date text, a float, b float);',
                        do_return=False
                    )
                    db.commit()

                    db.copy_expert(
                        query=f"copy {table_name} from stdin delimiter ',' csv header NULL as 'NULL'",
                        file='/home/hajali/Desktop/Bargh_Ml_project/temp/factors.csv',
                        mode='r'
                    )
                    db.commit()

                    db.__exit__()
                except psycopg2.Error as e:
                    logger.error()
                    if db.connection:
                        db.rollback()
                

                try:
                    db.__enter__()
                    
                    db.copy_expert(
                        query=f"copy {table_name} to stdout with delimiter ',' csv header NULL as 'NULL'",
                        file='/home/hajali/Desktop/Bargh_Ml_project/data/interim/factors.csv',
                        mode='w'
                    )

                    db.commit()

                    db.__exit__()

                except psycopg2.Error as e:
                    logger.error()
                    if db.connection:
                        db.rollback()
                

            case RawData.STATUS:
                table_name = 'status'
                df = self.clean(input_file=file.value, is_xlsx=False)

                try:
                    df[['id', 'code']] = df['FullUnitCode'].str.split('-', expand=True)
                    df.drop(columns=['FullUnitCode'], axis=1, inplace=True)
                    df = df[['id', 'code'] + [col for col in df.columns if col not in ['id', 'code']]]
                    max_indices = df.groupby(['id', 'code', 'Date', 'Hour', 'UnitStatusTypeCode'])['Revision'].idxmax()
                    result = df.loc[max_indices]
                    result.drop(columns=['Revision'], axis=1, inplace=True)
                    result.to_csv(path_or_buf='/home/hajali/Desktop/Bargh_Ml_project/temp/status.csv', sep=',', header=True, index=False, na_rep='NULL')
                    
                    db.execute(
                        query=f'create table if not exists {table_name} (id varchar(50), code varchar(50), date text, status varchar(10), );',
                        do_return=False
                    )
                    db.commit()

                    db.copy_expert(
                        query=f"copy {table_name} from stdin delimiter ',' csv header NULL as 'NULL'",
                        file='/home/hajali/Desktop/Bargh_Ml_project/temp/status.csv',
                        mode='r'
                    )
                    db.commit()

                    db.__exit__()
                except psycopg2.Error as e:
                    logger.error()
                    if db.connection:
                        db.rollback()
                

                try:
                    db.__enter__()
                    
                    db.copy_expert(
                        query=f"copy {table_name} to stdout with delimiter ',' csv header NULL as 'NULL'",
                        file='/home/hajali/Desktop/Bargh_Ml_project/data/interim/status.csv',
                        mode='w'
                    )

                    db.commit()

                    db.__exit__()

                except psycopg2.Error as e:
                    logger.error()
                    if db.connection:
                        db.rollback()

In [24]:
man = csvfile_manipulation()
# man.process(file=RawData.BAR)

In [25]:
man.process(file=RawData.PLANT)

2025-02-15 19:27:17,754 - src.data.dbconnection - INFO - a user connected to DB.

2025-02-15 19:27:17,787 - src.data.dbconnection - INFO - Successfully execute the query:
create table if not exists plant_data (id varchar(50), name varchar(100), type varchar(10), UTM text)
 on the DB.
2025-02-15 19:27:17,788 - src.data.dbconnection - INFO - Commitment successfully applied.
2025-02-15 19:27:17,790 - src.data.dbconnection - INFO - Successfully copied file /home/hajali/Desktop/Bargh_Ml_project/temp/plantdata.csv
2025-02-15 19:27:17,792 - src.data.dbconnection - INFO - Commitment successfully applied.
2025-02-15 19:27:17,793 - src.data.dbconnection - INFO - Connection to the DB cloesd.
2025-02-15 19:27:17,794 - src.data.dbconnection - INFO - User exited from DB.
2025-02-15 19:27:17,806 - src.data.dbconnection - INFO - a user connected to DB.
2025-02-15 19:27:17,807 - src.data.dbconnection - INFO - User reConnected to the DB
2025-02-15 19:27:17,808 - src.data.dbconnection - INFO - Successfully copied file /home/hajali/Desktop/Bargh_Ml_project/data/interim/plant_data.csv
2025-02-15 19:27:17,809 - src.data.dbconnection - INFO - Commitment successfully applied.
2025-02-15 19:27:17,809 - src.data.dbconnection - INFO - Connection to the DB cloesd.
2025-02-15 19:27:17,810 - src.data.dbconnection - INFO - User exited from DB.

In [54]:
a = RawData
print(type(a.BAR))

<enum 'RawData'>

In [4]:
df = drop_columns('../data/raw/PlantData.xlsx', ['DispPlantCode', 'PlantName', 'PlantType', 'UTM'])

Exception --""'utf-8' codec can't decode bytes in position 15-16: invalid continuation byte""-- occured and couldnt get the data.

In [4]:
! pip install psycopg2

Collecting psycopg2
  Using cached psycopg2-2.9.10.tar.gz (385 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: psycopg2
  Building wheel for psycopg2 (pyproject.toml) ... done
  Created wheel for psycopg2: filename=psycopg2-2.9.10-cp312-cp312-linux_x86_64.whl size=529568 sha256=41583a9efd286a9ee208122a1adede6873b224c51d4cd7d375780e126da4619a
  Stored in directory: /home/hajali/.cache/pip/wheels/ac/bb/ce/afa589c50b6004d3a06fc691e71bd09c9bd5f01e5921e5329b
Successfully built psycopg2
Installing collected packages: psycopg2
Successfully installed psycopg2-2.9.10

In [8]:
! pip install pyyaml

Collecting pyyaml
  Downloading PyYAML-6.0.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)
Downloading PyYAML-6.0.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (767 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 767.5/767.5 kB 1.7 MB/s eta 0:00:00[36m0:00:01m eta 0:00:01m
Installing collected packages: pyyaml
Successfully installed pyyaml-6.0.2

In [8]:
import psycopg2
import yaml

In [9]:
class Database:
    def __init__(self):
        self.connection_parameters = {
            key: value for key, value in yaml.load(open('/home/hajali/Desktop/Bargh_Ml_project/configs/database.yaml'), Loader=yaml.SafeLoader).items()
            }
        self.connection = None
    
    def connect(self):
        if self.connection is None:
            self.connection = psycopg2.connect(**self.connection_parameters)
    
    def close(self):
        if self.connection:
            self.connection.close()
            self.connection = None
    
    def execute(self, query:str, params=None):
        with self.connection.cursor() as cursor:
            cursor.execute(query, params)
            return cursor.fetchall()
    
    def commit(self):
        if self.connection:
            self.connection.commit()
    
    def rollback(self):
        if self.connection:
            self.connection.rollback()
    
    def __enter__(self):
        self.connect()
        return self
    
    def __exit__(self):
        self.close()

In [10]:
db = Database()
db.connect()
result = db.execute("SELECT * from final limit 10;")
print(result)

[('1001', 'زاهدان', 'G11', datetime.date(1403, 7, 7), 1, 15.818547, 'SO', 16.88, 18.0, [0.0, 12.0, 137.0, 15.4, 136.2, 0.0, 10.6, 134.0]), ('1001', 'زاهدان', 'G11', datetime.date(1403, 7, 4), 1, 16.916451, 'SO', 23.15, 17.0, [14.0, 15.0, 134.8, 13.0, 10.5, 15.1, 131.3, 0.0, 15.0, 12.0, 133.0, 136.0, 14.0]), ('1001', 'زاهدان', 'G11', datetime.date(1403, 7, 1), 1, 17.011222, 'SO', 24.08, 17.0, [134.8, 11.0, 14.0, 0.0, 15.1, 14.0, 15.0, 133.0, 13.0, 15.0, 136.0, 131.3, 12.0]), ('1001', 'زاهدان', 'G11', datetime.date(1403, 7, 3), 1, 17.053342, 'SO', 22.35, 17.0, [137.0, 134.0, 134.8, 10.5, 0.0, 131.3, 12.0, 15.0, 13.0, 15.1, 14.0, 15.0, 14.0]), ('1001', 'زاهدان', 'G11', datetime.date(1403, 7, 2), 1, 17.16982, 'SO', 22.48, 17.0, [15.0, 0.0, 131.3, 12.0, 10.5, 134.8, 15.0, 13.0, 134.0, 15.1, 14.0, 14.0, 137.0]), ('1001', 'زاهدان', 'G11', datetime.date(1403, 7, 6), 1, 17.170651, 'SO', 20.33, 18.0, [20.0, 137.0, 10.0, 14.0, 13.0, 15.0, 131.3, 0.0, 15.5, 12.0, 134.0, 14.0, 0.0, 15.0]), ('1001', 'زاهدان', 'G11', datetime.date(1403, 7, 5), 1, 17.189033, 'SO', 21.3, 18.0, [133.0, 20.0, 134.8, 131.3, 14.0, 15.0, 13.0, 15.0, 12.0, 15.5, 10.5, 14.0, 0.0, 136.0]), ('1001', 'زاهدان', 'G11', datetime.date(1403, 7, 10), 1, 17.541514, 'SO', 18.25, 18.0, [14.0]), ('1001', 'زاهدان', 'G11', datetime.date(1403, 7, 8), 1, 17.834511, 'SO', 17.45, 18.0, [20.0, 14.0, 14.0, 136.0, 12.0, 15.0, 15.2, 15.0, 133.0, 10.4, 0.0, 136.2, 13.0, 0.0]), ('1001', 'زاهدان', 'G11', datetime.date(1403, 7, 9), 1, 17.86333, 'SO', 16.68, 18.0, [133.0, 136.0, 14.0, 14.0, 13.0, 15.0, 12.0, 0.0, 136.2, 0.0, 10.1, 15.2, 15.0])]

In [ ]:
with open('../configs/database.yaml', 'r') as f:
    data = yaml.safe_load(f)

conn = psycopg2.connect(
    dbname=data.get('dbname'),
    user=data.get('user'),
    password=data.get('password'),
    host=data.get('host'),
    port=data.get('port')
)



# conn = psycopg2.connect(
#     dbname='postgres',
#     user='postgres',
#     password='aghd2091380',
#     host='localhost',
#     port='5432'
# )

cursor = conn.cursor()

cursor.execute("SELECT * from final limit 10;")
result = cursor.fetchall()

cursor.close()
conn.close()

print(result)

[('1001', 'زاهدان', 'G11', datetime.date(1403, 7, 7), 1, 15.818547, 'SO', 16.88, 18.0, [0.0, 12.0, 137.0, 15.4, 136.2, 0.0, 10.6, 134.0]), ('1001', 'زاهدان', 'G11', datetime.date(1403, 7, 4), 1, 16.916451, 'SO', 23.15, 17.0, [14.0, 15.0, 134.8, 13.0, 10.5, 15.1, 131.3, 0.0, 15.0, 12.0, 133.0, 136.0, 14.0]), ('1001', 'زاهدان', 'G11', datetime.date(1403, 7, 1), 1, 17.011222, 'SO', 24.08, 17.0, [134.8, 11.0, 14.0, 0.0, 15.1, 14.0, 15.0, 133.0, 13.0, 15.0, 136.0, 131.3, 12.0]), ('1001', 'زاهدان', 'G11', datetime.date(1403, 7, 3), 1, 17.053342, 'SO', 22.35, 17.0, [137.0, 134.0, 134.8, 10.5, 0.0, 131.3, 12.0, 15.0, 13.0, 15.1, 14.0, 15.0, 14.0]), ('1001', 'زاهدان', 'G11', datetime.date(1403, 7, 2), 1, 17.16982, 'SO', 22.48, 17.0, [15.0, 0.0, 131.3, 12.0, 10.5, 134.8, 15.0, 13.0, 134.0, 15.1, 14.0, 14.0, 137.0]), ('1001', 'زاهدان', 'G11', datetime.date(1403, 7, 6), 1, 17.170651, 'SO', 20.33, 18.0, [20.0, 137.0, 10.0, 14.0, 13.0, 15.0, 131.3, 0.0, 15.5, 12.0, 134.0, 14.0, 0.0, 15.0]), ('1001', 'زاهدان', 'G11', datetime.date(1403, 7, 5), 1, 17.189033, 'SO', 21.3, 18.0, [133.0, 20.0, 134.8, 131.3, 14.0, 15.0, 13.0, 15.0, 12.0, 15.5, 10.5, 14.0, 0.0, 136.0]), ('1001', 'زاهدان', 'G11', datetime.date(1403, 7, 10), 1, 17.541514, 'SO', 18.25, 18.0, [14.0]), ('1001', 'زاهدان', 'G11', datetime.date(1403, 7, 8), 1, 17.834511, 'SO', 17.45, 18.0, [20.0, 14.0, 14.0, 136.0, 12.0, 15.0, 15.2, 15.0, 133.0, 10.4, 0.0, 136.2, 13.0, 0.0]), ('1001', 'زاهدان', 'G11', datetime.date(1403, 7, 9), 1, 17.86333, 'SO', 16.68, 18.0, [133.0, 136.0, 14.0, 14.0, 13.0, 15.0, 12.0, 0.0, 136.2, 0.0, 10.1, 15.2, 15.0])]

In [12]:
duplicate = df[df.duplicated()]
print(type(duplicate))

<class 'pandas.core.frame.DataFrame'>

In [8]:
a = {
    'a': {
        'c': 1,
        'd': 2
    },
    'b': 2
}
print(list(a['a'].keys())[0])

c

In [2]:
import yaml

In [6]:
# parameters = {
    # key: value for key, value in yaml.load(open('/home/hajali/Desktop/Bargh_Ml_project/configs/database.yaml'), Loader=yaml.SafeLoader).values()
# }

p = yaml.load(open('/home/hajali/Desktop/Bargh_Ml_project/configs/tables_columns.yaml'), Loader=yaml.SafeLoader)
print(type(p))
print(p.keys())

<class 'dict'>
dict_keys(['bar', 'plant_date', 'plant_temp', 'energy', 'selleroffer', 'factors', 'status'])

In [7]:
print(p['bar'])

{'bar': {'date': 'text', 'hour': 'int', 'value': 'varchar(10)'}}

In [20]:
print(dict(p['bar'].items()))
print(next(iter(p.values())))

{'bar': {'date': 'text', 'hour': 'int', 'value': 'varchar(10)'}}
{'bar': {'date': 'text', 'hour': 'int', 'value': 'varchar(10)'}}

In [22]:
def get_innermost_dict(nested_dict):

    if not isinstance(nested_dict, dict):
        return None  # Not a dictionary

    if not nested_dict:
        return None  # Empty dictionary

    first_value = next(iter(nested_dict.values()))  # Get the first value

    if isinstance(first_value, dict):
        # Recursively call the function if the first value is a dictionary
        return get_innermost_dict(first_value)
    else:
        # If the first value is not a dictionary, then the current dictionary
        # is the innermost dictionary.
        return nested_dict

inner = get_innermost_dict(p)
print(type(inner))

<class 'dict'>

In [26]:
import pandas as pd
import numpy as np

In [31]:
df = pd.read_csv('../data/interim/bar.csv')
df.head()

         date  hour value
0  1402/01/01     1     L
1  1402/01/01     2     L
2  1402/01/01     3     L
3  1402/01/01     4     L
4  1402/01/01     5     L

In [32]:
df = df.select_dtypes(include=np.number)

In [33]:
df.head()

   hour
0     1
1     2
2     3
3     4
4     5

In [1]:
a = 'ali'
a += '2'
print(a)

ali2

In [3]:
import yaml

with open('/home/hajali/Desktop/Bargh_Ml_project/configs/crawling.yaml') as file:
    data = yaml.safe_load(file)
    a = data['hourly']

print(a)
print(type(a))

['temperature_2m', 'relative_humidity_2m', 'dew_point_2m', 'apparent_temperature', 'precipitation_probability', 'precipitation', 'rain', 'snowfall', 'surface_pressure', 'evapotranspiration', 'wind_speed_10m', 'wind_direction_10m']
<class 'list'>

In [5]:
import pandas as pd

In [6]:
df = pd.read_csv('/home/hajali/Desktop/Bargh/csv_files/totalWeatherData.csv')
df.head()

,unitid,date,time,temperature_2m,relative_humidity_2m,dew_point_2m,apparent_temperature,precipitation,rain,snowfall,surface_pressure,evapotranspiration,wind_speed_10m,wind_direction_10m
0,MZ014,1403-07-01,24,13.233001,83,10.407692,12.891596,0.0,0.0,0,870.74854,0.0,3.259939,263.65990
1,MZ014,1403-07-01,1,12.783000,84,10.146644,12.313705,0.0,0.0,0,870.71110,0.0,3.617955,275.71050
2,MZ014,1403-07-01,2,12.533000,86,10.253708,12.044769,0.0,0.0,0,871.10864,0.0,3.960000,270.00000
3,MZ014,1403-07-01,3,12.633000,84,9.999721,11.964706,0.0,0.0,0,870.64150,0.0,4.693825,274.39862
4,MZ014,1403-07-01,4,15.133000,71,9.911569,14.485054,0.0,0.0,0,871.79470,0.0,4.379589,260.53775

In [7]:
print(type(df['date'][0]))

<class 'str'>

In [8]:
df['date'] = pd.to_datetime(df['date'])

df.loc[df['hour'] == 0, 'hour'] = 24
df.loc[df['hour'] == 24, 'date'] = df['date'] - pd.Timedelta(days=1)

/tmp/ipykernel_4563/602146803.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['date'] = pd.to_datetime(df['date'])

OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 1403-07-01, at position 0